wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1655581832
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      4: 3.8.12
      5: 0.12.18
      8:
      - 1
      - 5
